const listaContatos=[{
    "_id": {
      "$oid": "64e8a7a5f43f8e23d0883761"
    },
    "name": "Geísa Finger",
    "contact_type": "PF",
    "image_url": "https://media.licdn.com/dms/image/C4E03AQFYLO8N9GDnrg/profile-displayphoto-shrink_400_400/0/1556835293814?e=1698278400&v=beta&t=Xzdr5FqaXlqzB_p_JJwaVXepzz4tKqUH6uekIB6dzUo",
    "city": "Porto Alegre",
    "intern_contact": "--",
    "state": "RS",
    "profession": "Bióloga",
    "business_segment": "Analista de Desenvolvimento de Mercado Sênior na Bionat Soluções Biológicas",
    "email": "--",
    "phone": "--",
    "address_street": "--",
    "address_number": "--",
    "district": "--",
    "zip_code": "--",
    "complement": "--",
    "site": "--",
    "planting_culture": "TRIGO",
    "whatsapp": "--",
    "facebook": "--",
    "instagram": "--",
    "linkedin": "https://www.linkedin.com/in/ge%C3%ADsa-finger-3a8271130/",
    "specialties": "--",
    "degree_relevance": 3,
    "observation": null,
    "situation": "ATIVA"
  },
  {
    "_id": {
      "$oid": "64e8a7a5f43f8e23d0883762"
    },
    "name": "Fernando Dubou Hansel",
    "contact_type": "PF",
    "image_url": "https://media.licdn.com/dms/image/C4E03AQFZIUZ3LdgusA/profile-displayphoto-shrink_400_400/0/1582905328090?e=1698278400&v=beta&t=rpWmkKB2CYnpDRw_7vmShDmr41WkPlvGInKkNsnEC6E",
    "city": "Passo Fundo",
    "intern_contact": "--",
    "state": "RS",
    "profession": "PESQUISADOR",
    "business_segment": "Pesquisas com manejo de fertilizantes para o aumento produtivo e sustentável das culturas.",
    "email": "--",
    "phone": "--",
    "address_street": "--",
    "address_number": "--",
    "district": "--",
    "zip_code": "--",
    "complement": "--",
    "site": "--",
    "planting_culture": "TRIGO",
    "whatsapp": "--",
    "facebook": "--",
    "instagram": "--",
    "linkedin": "https://www.linkedin.com/in/fernando-dubou-hansel-b25567127/?locale=pt_BR",
    "specialties": null,
    "degree_relevance": 3,
    "observation": null,
    "situation": "ATIVA"
  },
  {
    "_id": {
      "$oid": "64e8a7a5f43f8e23d0883763"
    },
    "name": "Instituto Bélgica-Nova Friburgo (Ibelga)",
    "contact_type": "PJ",
    "image_url": "https://www.ibelga.org.br/tpl/images/logo.png",
    "city": "Nova Friburgo",
    "intern_contact": "Ricardo van Hombeeck",
    "state": "RJ",
    "profession": "--",
    "business_segment": "Fundaram o IBELGA, o DISOP – Serviço Internacional de Cooperação aos Projetos de Desenvolvimento- e o IDES - Instituto para o Desenvolvimento Econômico, Educacional, Social e Cultural de Nova Friburgo, inaugurando a primeira Fazenda Escola Rei Alberto I , aplicando a pedagogia da alternância, em 1º de março de 1994, oferecendo o segundo segmento do ENSINO FUNDAMENTAL om 39 alunos . Em 1998, atendendo forte reivindicação da comunidade, foi implantado o ENSINO MÉDIO com a EDUCAÇÃO PROFISSIONAL, oferecendo o curso de Técnico em Agropecuária, e em 2010 teve início o curso Profissionalizante de Técnico em Administração.",
    "email": "ceareialberto@gmail.com/cmceffaflores@gmail.com",
    "phone": "(22) 2523-5005/(22) 2543-6907",
    "address_street": "Estrada Dos Três Picos",
    "address_number": "s/n",
    "district": "Baixada de Salinas",
    "zip_code": "--",
    "complement": "--",
    "site": "https://www.ibelga.org.br/faleconosco",
    "planting_culture": "HORTIFRUTI",
    "whatsapp": "--",
    "facebook": "--",
    "instagram": "--",
    "linkedin": "https://www.linkedin.com/in/ricardo-van-hombeeck-ba992271/?originalSubdomain=br",
    "specialties": "Escola Agrícola",
    "degree_relevance": 4,
    "observation": null,
    "situation": "ATIVA"
  },
  {
    "_id": {
      "$oid": "64e8a7a5f43f8e23d0883764"
    },
    "name": "TMF Fertilizantes",
    "contact_type": "PJ",
    "image_url": "https://tmffertilizantes.com.br/",
    "city": "PAINS",
    "intern_contact": null,
    "state": "MG",
    "profession": "--",
    "business_segment": "Fertilizante Especial de Múltipla Ação, capaz de corrigir, construir e manter a fertilidade do solo em todo seu perfil, além de nutrir plantas para alcançar altas produtividades.",
    "email": "contato@tmffertilizantes.com.br",
    "phone": "(37) 3323-2182 | (37) 3323-2216",
    "address_street": "Rod. MG 170",
    "address_number": "KM 87",
    "district": "--",
    "zip_code": "--",
    "complement": "--",
    "site": "https://tmffertilizantes.com.br/fale-conosco/",
    "planting_culture": "ALGODÃO/CANA/CAFÉ/HORTI/SOJA/FUMO",
    "whatsapp": "--",
    "facebook": "--",
    "instagram": "--",
    "linkedin": "https://www.linkedin.com/company/tmffertilizantes/",
    "specialties": "Fertilizantes",
    "degree_relevance": 4,
    "observation": null,
    "situation": "ATIVA"
  }]
module.exports = listaContatos;
